# Generated by Django 3.0.8 on 2020-07-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisement', '0002_advertisers'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisers',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
