# Generated by Django 3.0.8 on 2020-07-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisement', '0003_advertisers_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisers',
            name='page_created_date',
            field=models.DateField(blank=True),
        ),
    ]
