# Generated by Django 3.0.8 on 2020-07-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisement', '0004_auto_20200727_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
