# Generated by Django 3.0.8 on 2020-08-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisement', '0005_advertisers_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisers',
            name='fb_page_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
