# Generated by Django 3.0.8 on 2020-08-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisement', '0006_advertisers_fb_page_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='hide',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
