# Generated by Django 3.0.8 on 2020-08-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisement', '0007_auto_20200804_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisers',
            name='company_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='advertisers',
            name='page_created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisers',
            name='page_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
