# Generated by Django 3.0.8 on 2020-08-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisement', '0008_auto_20200804_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisers',
            name='fb_page_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
